name: Prod Automate Build-Push, Update-Task

on:
  workflow_dispatch:

env:
  BRAND_NAME: "TOUFIK"
  AWS_REGION: "ap-south-1"
  ECR_REGISTRY: "metabase"
  ECR_REPOSITORY: "metabase"
  ECS_SERVICE: "stage-metabase-service"
  ECS_CLUSTER: "demo"
  ECS_TASK_DEFINITION: "stage-metabase-task"
  CONTAINER_NAME: "metabase"

  MB_DB_HOST: "${{ secrets.MB_DB_HOST }}"
  MB_DB_PORT: "${{ secrets.MB_DB_PORT }}"
  MB_DB_DBNAME: "${{ secrets.MB_DB_DBNAME }}"
  MB_DB_USER: "${{ secrets.MB_DB_USER }}"
  MB_DB_PASS: "${{ secrets.MB_DB_PASS }}"

jobs:
  create-json:
    name: Generate JSON File
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Convert All Global `env` Variables to JSON
        run: |
          echo "{" > env.json
          printenv | grep '^MB_DB_' | awk -F= '{print "  \""$1"\": \""$2"\","}' >> env.json
          sed -i '$ s/,$//' env.json  # Remove the last comma
          echo "}" >> env.json

      - name: Display JSON File
        run: cat env.json

      - name: Upload JSON as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: environment-variables
          path: env.json

