name: Prod Automate Build-Push, Update-Task

on:
  workflow_dispatch:

env:
  BRAND_NAME: "TOUFIK"
  AWS_REGION: "ap-south-1"
  ECR_REGISTRY: "metabase"
  ECR_REPOSITORY: "metabase"
  ECS_SERVICE: "stage-metabase-service"
  ECS_CLUSTER: "demo"
  ECS_TASK_DEFINITION: "stage-metabase-task"
  CONTAINER_NAME: "metabase"

  ENVIRONMENT_VARIABLES: '[
    {"name": "MB_DB_HOST", "value": "${{ secrets.MB_DB_HOST }}"},
    {"name": "MB_DB_PORT", "value": "${{ secrets.MB_DB_PORT }}"},
    {"name": "MB_DB_DBNAME", "value": "${{ secrets.MB_DB_DBNAME }}"},
    {"name": "MB_DB_USER", "value": "${{ secrets.MB_DB_USER }}"},
    {"name": "MB_DB_PASS", "value": "${{ secrets.MB_DB_PASS }}"}
  ]'

jobs:
  create-json:
    name: Generate JSON File
    runs-on: ubuntu-latest  # ✅ Uses a stable runner version

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Convert `ENVIRONMENT_VARIABLES` to JSON
        run: |
          echo '${{ env.ENVIRONMENT_VARIABLES }}' | jq '.' > env.json

      - name: Display JSON File
        run: cat env.json

      - name: Upload JSON as Artifact
        uses: actions/upload-artifact@v4  # ✅ Updated to v4
        with:
          name: environment-variables
          path: env.json
