name: Deploy to ECS
on: workflow_dispatch

# Centralized environment configuration
env:
  AWS_REGION: "ap-south-1"
  ECR_REGISTRY: "metabase"
  ECR_REPOSITORY: "metabase"
  ECS_SERVICE: "stage-metabase-service"
  ECS_CLUSTER: "demo"
  ECS_TASK_DEFINITION: "stage-metabase-task"
  CONTAINER_NAME: "metabase"
  BRAND_NAME: "TOUFIK"

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Environment Variables JSON
        id: generate-env
        run: |
          ENV_JSON=$(jq -n \
            --arg db_host "${{ secrets.MB_DB_HOST }}" \
            --arg db_port "${{ secrets.MB_DB_PORT }}" \
            --arg db_name "${{ secrets.MB_DB_DBNAME }}" \
            --arg db_user "${{ secrets.MB_DB_USER }}" \
            --arg db_pass "${{ secrets.MB_DB_PASS }}" \
            '[{name: "MB_DB_HOST", value: $db_host}, {name: "MB_DB_PORT", value: $db_port}, {name: "MB_DB_DBNAME", value: $db_name}, {name: "MB_DB_USER", value: $db_user}, {name: "MB_DB_PASS", value: $db_pass}]')
          echo "ENV_JSON=$ENV_JSON" >> $GITHUB_OUTPUT

      - name: Trigger Reusable Workflow
        uses: ./.github/workflows/update-task.yml
        with:
          aws_region: ${{ env.AWS_REGION }}
          brand_name: ${{ env.BRAND_NAME }}
          environment_variables: ${{ steps.generate-env.outputs.ENV_JSON }}
        secrets:
          AWS_ACCESS_KEY_ID: ${{ secrets.TOUFIK_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TOUFIK_AWS_SECRET_ACCESS_KEY }}
