name: Prod Automate Build-Push, Update-Task

on:
  workflow_dispatch:

env:
  BRAND_NAME: "TOUFIK"
  AWS_REGION: "ap-south-1"
  ECR_REGISTRY: "metabase"
  ECR_REPOSITORY: "metabase"
  ECS_SERVICE: "stage-metabase-service"
  ECS_CLUSTER: "demo"
  ECS_TASK_DEFINITION: "stage-metabase-task"
  CONTAINER_NAME: "metabase"

permissions:
  contents: read

jobs:
  get-env-vars:
    runs-on: ubuntu-latest
    outputs:
      environment_vars: ${{ steps.generate-env.outputs.env_json }}
    steps:
      - name: Generate Environment Variables
        id: generate-env
        run: |
          ENV_JSON=$(jq -n \
            --arg db_host "${{ secrets.MB_DB_HOST }}" \
            --arg db_port "${{ secrets.MB_DB_PORT }}" \
            --arg db_name "${{ secrets.MB_DB_DBNAME }}" \
            --arg db_user "${{ secrets.MB_DB_USER }}" \
            --arg db_pass "${{ secrets.MB_DB_PASS }}" \
            '[{name: "MB_DB_HOST", value: $db_host}, {name: "MB_DB_PORT", value: $db_port}, {name: "MB_DB_DBNAME", value: $db_name}, {name: "MB_DB_USER", value: $db_user}, {name: "MB_DB_PASS", value: $db_pass}]')
          echo "env_json=$ENV_JSON" >> $GITHUB_OUTPUT

  update-ecs-task-and-service:
    needs: get-env-vars
    uses: ./.github/workflows/update-task.yml
    with:
      brand_name: ${{ env.BRAND_NAME }}
      aws_region: ${{ env.AWS_REGION }}
      environment_vars: ${{ needs.get-env-vars.outputs.environment_vars }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.TOUFIK_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TOUFIK_AWS_SECRET_ACCESS_KEY }}
