name: Update ECS Task Definition and Deploy to ECS

on:
  workflow_call:
    inputs:
      
      ECR_REGISTRY:
        description: 'The Amazon ECS cluster name'
        required: true
        type: string

      ECR_REPOSITORY:
        description: 'The Amazon ECS cluster name'
        required: true
        type: string  

      ECS_CLUSTER_NAME:
        description: 'The Amazon ECS cluster name'
        required: true
        type: string

      ECS_TASK_DEFINITION:
        description: 'The Amazon ECS task def name'
        required: true
        type: string

      ECS_SERVICE_NAME:
        description: 'The Amazon ECS service name'
        required: true
        type: string

      CONTAINER_NAME:
        description: 'The Amazon ECS container name'
        required: true
        type: string
  
      aws_region:
        description: 'The AWS region'
        required: true
        type: string

      brand_name:
        description: 'select the brand'
        required: true
        type: string

      # ENVIRONMENT_VARIABLES:
      #   description: 'envs required for task'
      #   type: string  
jobs:
  update-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download JSON File
        uses: actions/download-artifact@v4
        with:
          name: environment-variables
          path: .

      - name: Confirm JSON File Transfer
        run: |
          if [ -f "env.json" ]; then
            echo "✅ JSON file transferred successfully!"
          else
            echo "❌ JSON file is missing!"
            exit 1
          fi

      - name: Display JSON File
        run: cat env.json

      - name: Render ECS Task Definition
        run: |
          jq '.containerDefinitions[0].environment |= $ENV_VARS' \
            --argjson ENV_VARS "$(cat env.json)" task-definition.json > new-task-definition.json

      - name: Display Updated Task Definition
        run: cat new-task-definition.json
