name: Update ECS Task Definition and Deploy to ECS

on:
  workflow_call:
    inputs:
      
      ECR_REGISTRY:
        description: 'The Amazon ECS cluster name'
        required: true
        type: string

      ECR_REPOSITORY:
        description: 'The Amazon ECS cluster name'
        required: true
        type: string  

      ECS_CLUSTER_NAME:
        description: 'The Amazon ECS cluster name'
        required: true
        type: string

      ECS_TASK_DEFINITION:
        description: 'The Amazon ECS task def name'
        required: true
        type: string

      ECS_SERVICE_NAME:
        description: 'The Amazon ECS service name'
        required: true
        type: string

      CONTAINER_NAME:
        description: 'The Amazon ECS container name'
        required: true
        type: string
  
      aws_region:
        description: 'The AWS region'
        required: true
        type: string

      brand_name:
        description: 'select the brand'
        required: true
        type: string

      # ENVIRONMENT_VARIABLES:
      #   description: 'envs required for task'
      #   type: string  
jobs:
  update-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download JSON File
        uses: actions/download-artifact@v4
        with:
          name: environment-variables
          path: .

      - name: Confirm JSON File Transfer
        run: |
          if [ -f "env.json" ]; then
            echo "✅ JSON file transferred successfully!"
          else
            echo "❌ JSON file is missing!"
            exit 1
          fi

      - name: Display JSON File
        run: cat env.json

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.TOUFIK_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TOUFIK_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
          
      - name: Get the Current ECS Task Definition
        id: get-task-def
        run: |
          aws ecs describe-task-definition --task-definition ${{ inputs.ECS_TASK_DEFINITION }} --query taskDefinition > task-definition.json
      
      - name: Parse `env.json` and Format Environment Variables
        id: parse-env
        run: |
          echo "ENV_VARS<<"EOF" >> $GITHUB_ENV
          jq -r 'map("\(.name)=\(.value)") | join("\n")' env.json >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
      - name: Debug - Print Extracted Environment Variables
        run: echo "$ENV_VARS"


      - name: Render New ECS Task Definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ inputs.CONTAINER_NAME }}
          image: ${{ inputs.ECR_REGISTRY }}/${{ inputs.ECR_REPOSITORY }}:${{ inputs.NEW_IMAGE_TAG }}
          environment-variables: ${{ env.ENV_VARS }}

      - name: Deploy Amazon ECS Task Definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ inputs.ECS_SERVICE_NAME }}
          cluster: ${{ inputs.ECS_CLUSTER_NAME }}
          wait-for-service-stability: true

      - name: Display Updated Task Definition
        run: cat new-task-definition.json
