name: Update ECS Task
on:
  workflow_call:
    inputs:
      aws_region:
        required: true
        type: string
      brand_name:
        required: true
        type: string
      environment_variables:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

# Reusable envs to avoid repetition
env:
  ECR_REGISTRY: "metabase"
  ECR_REPOSITORY: "metabase"
  ECS_SERVICE: "stage-metabase-service"
  ECS_CLUSTER: "demo"
  ECS_TASK_DEFINITION: "stage-metabase-task"
  CONTAINER_NAME: "metabase"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}

      - name: Render Task Definition
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}
          environment-variables: ${{ inputs.environment_variables }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
