name: Update ECS Task Definition

on:
  workflow_call:
    inputs:
      brand_name:
        required: true
        type: string
      aws_region:
        required: true
        type: string
      environment_vars:
        required: false
        type: string

jobs:
  update-task:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # - name: Debug - Print ENVIRONMENT_VARIABLES
      #   run: echo "Received ENVIRONMENT_VARIABLES: $ENVIRONMENT_VARIABLES"

      - name: Write ENVIRONMENT_VARIABLES to JSON File
        run: echo "$ENVIRONMENT_VARIABLES" > env.json

      - name: Update ECS Task Definition
        run: |
          NEW_TASK_DEF=$(jq --argjson ENV_VARS "$(cat env.json)" \
            '.containerDefinitions[0].environment |= $ENV_VARS' task-definition.json)
          echo "$NEW_TASK_DEF" > new-task-definition.json
