name: Update ECS Task Definition and Deploy to ECS

on:
  workflow_call:
    inputs:
      
      ECR_REGISTRY:
        description: 'The Amazon ECS cluster name'
        required: true
        type: string

      ECR_REPOSITORY:
        description: 'The Amazon ECS cluster name'
        required: true
        type: string  

      ECS_CLUSTER_NAME:
        description: 'The Amazon ECS cluster name'
        required: true
        type: string

      ECS_TASK_DEFINITION:
        description: 'The Amazon ECS task def name'
        required: true
        type: string

      ECS_SERVICE_NAME:
        description: 'The Amazon ECS service name'
        required: true
        type: string

      CONTAINER_NAME:
        description: 'The Amazon ECS container name'
        required: true
        type: string
  
      aws_region:
        description: 'The AWS region'
        required: true
        type: string

      brand_name:
        description: 'select the brand'
        required: true
        type: string

      # ENVIRONMENT_VARIABLES:
      #   description: 'envs required for task'
      #   type: string  
jobs:
  update-task:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # - name: Debug - Print ENVIRONMENT_VARIABLES
      #   run: echo "Received ENVIRONMENT_VARIABLES: $ENVIRONMENT_VARIABLES"

      - name: Write ENVIRONMENT_VARIABLES to JSON File
        run: echo "$ENVIRONMENT_VARIABLES" > env.json

      - name: Update ECS Task Definition
        run: |
          NEW_TASK_DEF=$(jq --argjson ENV_VARS "$(cat env.json)" \
            '.containerDefinitions[0].environment |= $ENV_VARS' task-definition.json)
          echo "$NEW_TASK_DEF" > new-task-definition.json
