name: Update ECS Task Definition

on:
  workflow_call:
    inputs:
      brand_name:
        required: true
        type: string
      aws_region:
        required: true
        type: string
      environment_vars:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  update-task:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Debug - Print ENVIRONMENT_VARIABLES
        run: echo "Received ENVIRONMENT_VARIABLES: $ENVIRONMENT_VARIABLES"

      - name: Update ECS Task Definition
        run: |
          echo "[${ENVIRONMENT_VARIABLES}]" > env.json
          NEW_TASK_DEF=$(jq '.containerDefinitions[0].environment |= $ENV_VARS' \
            --argjson ENV_VARS "$(cat env.json)" \
            task-definition.json)
          echo "$NEW_TASK_DEF" > new-task-definition.json
